import type { Metadata } from "next"

import 'bootstrap/dist/css/bootstrap.css'
import "./globalStyles/globals.css"
import './globalStyles/footer.css'
import Layout from "@/components/layouts/Layouts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}

